# General
name: Henrik Klarup
info: Cand. Polyt. Software Aalborg University &nbsp;â€¢&nbsp; Seeking oppotunities
description: "Tech, software and other computer related stuff"
url: http://henrikklarup.github.io/

markdown: redcarpet
highlighter: pygments

paginate: 5
permalink: /:title

# Social share and comments.
disqus-id: henrikklarup
twitter: henrikklarup
github: henrikklarup
google: +henrikklarup

# RSS feed
rss-feed-limit: 10
rss-show-full: "no"
